### ISSUE TITLE
set bounce Index limit to 10, editor crashes

### ISSUE THREAD

**Issue by HybridEmotion** [INedelcu/RayTracingSRP#1]
Hello, 

This is an amazing project! Thank you for your share!

I play around this project, and modified `if (payload.bounceIndex < 5)` for more iteration. When I set it to 10, editor crashes.

I thought it is because of too much calculation. I removed refract part and get the same crash.

Could you give me a direction for more information related to this? And could I use this project for commercial usage? This is really interesting effect. There must be ways to create an amazing game out of it.

Thank you!

**Comment by INedelcu** [comment]
Hi!
You probably need to increase max_recursion_depth in the raytrace file
https://github.com/INedelcu/RayTracingSRP/blob/main/Assets/Shaders/RayGenerator.raytrace. The GPU needs to know in advance how much memory to allocate for rays.
You can use the projects in any way you want including making $ out of it 🤑

**Comment by HybridEmotion** [comment]
Thank you so much! I think `max_recursion_depth` should work.
