### ISSUE TITLE
Where can we find document about shader functions like TraceRay 

### ISSUE THREAD

**Issue by HybridEmotion** [INedelcu/RayTracingSRP#2]
Hello

I try to implement shader which does not cast shadow. Is there any difference between shaders in unity and [DXR](https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#traceray)?

Should I modify both `RayGenerator.raytrace` and `Diffuse.shader` to create material, which casts shadow with alpha, and material, does not cast any shadow.

Thank you!

**Comment by HybridEmotion** [comment]
by creating `anyhit_main` with `IgnoreHit()`?

**Comment by INedelcu** [comment]
TraceRay is a HLSL functions not a Unity function. It's defined by [Shader Model 6.3](https://github.com/microsoft/DirectXShaderCompiler/wiki/Shader-Model-6.3).

You can find it on Microsoft's site https://learn.microsoft.com/en-us/windows/win32/direct3d12/traceray-function or in DXR specification https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html

I recommend you reading a bit about how DXR works from the specs and how the raygen, miss, closest hit and any hit shaders interact with each other.

If you want to use alpha testing then you need an any hit shader defined where the closest hit shader is defined. It's only in .shader files where you can sample vertex attributes like UVs and read textures or any other material information. Just make sure that any hit shaders are actually executed. For this there's a few options. You can for example define a Render Queue range for alpha tested geometries and let [CullInstances](https://docs.unity3d.com/2023.1/Documentation/ScriptReference/Rendering.RayTracingAccelerationStructure.CullInstances.html) know about this range by configuring it in [cullingConfig.alphaTestedMaterialConfig](https://docs.unity3d.com/2023.1/Documentation/ScriptReference/Rendering.RayTracingInstanceMaterialConfig.html). For example:

cullingConfig.alphaTestedMaterialConfig.renderQueueLowerBound = 2400;
cullingConfig.alphaTestedMaterialConfig.renderQueueUpperBound = 2500;

![Unity_4n09XP2ZHy](https://user-images.githubusercontent.com/74784626/231110882-c1695ebf-ffbc-47c1-ab0a-82a1ea7a67cd.png)

If the material uses a render queue in this range, then it will enable any hit shaders.

An example:

```
Texture2D<float4> _MainTex;
SamplerState sampler_MainTex;

float4 _MainTex_ST;
float _Cutoff;

[shader("anyhit")]
void AnyHitMain(inout RayPayload payload : SV_RayPayload, AttributeData attribs : SV_IntersectionAttributes)
{
   uint3 triangleIndices = UnityRayTracingFetchTriangleIndices(PrimitiveIndex());

   Vertex v0, v1, v2;
   v0 = FetchVertex(triangleIndices.x);
   v1 = FetchVertex(triangleIndices.y);
   v2 = FetchVertex(triangleIndices.z);

   float3 barycentricCoords = float3(1.0 - attribs.barycentrics.x - attribs.barycentrics.y, attribs.barycentrics.x, attribs.barycentrics.y);

   Vertex v = InterpolateVertices(v0, v1, v2, barycentricCoords);

   float alpha = _MainTex.SampleLevel(sampler_MainTex, v.uv * _MainTex_ST.xy + _MainTex_ST.zw, 0).w;

   if (alpha < _Cutoff)
       IgnoreHit();
}

```
and the material properties are defined in the Properties block.

```
Properties
{
    _MainTex ("Texture", 2D) = "white" {}
    _Cutoff ("Alpha Cutoff", Float) = 0.5
}
```

**Comment by HybridEmotion** [comment]
@INedelcu Thank you! I want to achieve “accepting ray in render loop and ignoring hit in shadow loop". I failed to use alpha texture to implement my effect.

Instead, I did a hack. I used `anyhit` and `RayPayloadShadow` to check if current pass is shader pass. I think this way is not elegant.

But I could not find `RayPayloadShadow` struct in dxr document or unity built in shader. Where could I find these struct?

Previously, I try to implement similar 2 function of `[shader("miss")]` , 1 for RayPayload  and 1 for RayPayloadShadow. But writing 2 `[shader("anyhit")]` get instant crash in unity. I guess "miss" and "anyhit" are different, or there might be some pattern in unity to write 2  `[shader("anyhit")]`, which does not crash unity.

**Comment by INedelcu** [comment]
It's not possible to have 2 any hit shaders. 

All shader code is defined in the project files.

https://github.com/INedelcu/RayTracingSRP/blob/main/Assets/Shaders/RayPayload.hlsl for payload definitions.

Usually the effects in ray tracing are separated. In HDRP for example there are different effects for ray traced reflections, AO, shadows, etc. and their results are combined. In HDRP path tracing, there's a single payload since path tracing does all the effects in one go. 

Normally you have a raygeneration that matches a miss shader and a ShaderPass that I set using this line

`ctx.cmd.SetRayTracingShaderPass(renderPipelineAsset.rayTracingShader, "Test");`

The ray payload definitions must match between ray generation shader (where you first call TraceRay) and the ray payload definition from the closest hit and any hit shaders.

In my example from this project I don't do alpha testing and don't have any hit shaders.

**Comment by HybridEmotion** [comment]
> It's not possible to have 2 any hit shaders.
> 
> All shader code is defined in the project files.
> 
> https://github.com/INedelcu/RayTracingSRP/blob/main/Assets/Shaders/RayPayload.hlsl for payload definitions.
> 
> Usually the effects in ray tracing are separated. In HDRP for example there are different effects for ray traced reflections, AO, shadows, etc. and their results are combined. In HDRP path tracing, there's a single payload since path tracing does all the effects in one go.
> 
> Normally you have a raygeneration that matches a miss shader and a ShaderPass that I set using this line
> 
> `ctx.cmd.SetRayTracingShaderPass(renderPipelineAsset.rayTracingShader, "Test");`
> 
> The ray payload definitions must match between ray generation shader (where you first call TraceRay) and the ray payload definition from the closest hit and any hit shaders.
> 
> In my example from this project I don't do alpha testing and don't have any hit shaders.

Oh!!! I just missed the definitions in project. 

In my current project, there are ray generations for raypayload and raypayloadShadow, and shader has `any hit shader` for `raypayloadShadow` and `closest shader` for `raypayload`. `any hit shader` and `closest shader` does not use the same payload, but with the same ` : SV_RayPayload`.

**Comment by HybridEmotion** [comment]
> > It's not possible to have 2 any hit shaders.
> > All shader code is defined in the project files.
> > https://github.com/INedelcu/RayTracingSRP/blob/main/Assets/Shaders/RayPayload.hlsl for payload definitions.
> > Usually the effects in ray tracing are separated. In HDRP for example there are different effects for ray traced reflections, AO, shadows, etc. and their results are combined. In HDRP path tracing, there's a single payload since path tracing does all the effects in one go.
> > Normally you have a raygeneration that matches a miss shader and a ShaderPass that I set using this line
> > `ctx.cmd.SetRayTracingShaderPass(renderPipelineAsset.rayTracingShader, "Test");`
> > The ray payload definitions must match between ray generation shader (where you first call TraceRay) and the ray payload definition from the closest hit and any hit shaders.
> > In my example from this project I don't do alpha testing and don't have any hit shaders.
> 
> Oh!!! I just missed the definitions in project.
> 
> In my current project, there are ray generations for raypayload and raypayloadShadow, and shader has `any hit shader` for `raypayloadShadow` and `closest shader` for `raypayload`. `any hit shader` and `closest shader` does not use the same payload, but with the same ` : SV_RayPayload`.

I add custom field into RayPayload and resolve "miss shader and closest shader does not input the same RayPayload struct".

**Comment by INedelcu** [comment]
I believe that SV_RayPayload is not required anymore. It was a HLSL semantic required by DirectX Compiler at some point but now is ignored. You can try remove it in your version.

**Comment by HybridEmotion** [comment]
> I believe that SV_RayPayload is not required anymore. It was a HLSL semantic required by DirectX Compiler at some point but now is ignored. You can try remove it in your version.

Yes! I remove `SV_RayPayload` and `SV_IntersectionAttributes`. It works without any issue.
